### ISSUE TITLE
WARNING: SCDoc: In Applications/SuperCollider.app/Contents/Resources/HelpSource/Classes/UGen.schelp

### ISSUE THREAD

**Issue by prko** [supercollider-quarks/MathLib#43] opened 2023-11-08 14:11 UTC
Hello, 

Please see the following topic:
https://github.com/supercollider/supercollider/issues/6129

I could fix it, but I think it should be checked by the author!
Thank you.

**Comment by joslloand** [comment] 2023-11-08 19:06
Duplicate of https://github.com/supercollider-quarks/MathLib/issues/41

**Comment by dyfer** [comment] 2023-11-11 12:54
Closing as a duplicate.

**Closed as completed by dyfer** 2023-11-11 12:54 UTC
